### PR TITLE
Fix incorrect date label on monthly view on example file(fix #553)

### LINKED ISSUE #553: the month March does not appear in the label Month
The display of the month March does not appear in the label Month! 2020.02 instead of [2020.03]([url](
tui_bug

### PR DESCRIPTION
**Pull request by jungeun-cho**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* fix: when move to prev calendar in monthly view resolve incorrect displayed range text date label on examples(fix #553)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: examples/js/app.js [hunk 1]
```diff
@@ -372,16 +372,23 @@
         calendarTypeIcon.className = iconClassName;
     }
 
+    function currentCalendarDate(format) {
+      var currentDate = moment([cal.getDate().getFullYear(), cal.getDate().getMonth(), cal.getDate().getDate()]);
+
+      return format ? currentDate.format(format) : currentDate;
```
Comment (dongsik-yoo) [inline examples/js/app.js:378]: format is mandatory.  tenary operator is unnecessary.

File: examples/js/app.js [hunk 2]
```diff
@@ -372,16 +372,23 @@
         calendarTypeIcon.className = iconClassName;
     }
 
+    function currentCalendarDate(format) {
+      var currentDate = moment([cal.getDate().getFullYear(), cal.getDate().getMonth(), cal.getDate().getDate()]);
```
Comment (dongsik-yoo) [inline examples/js/app.js:376]: OK. You use only year, month, date to escapse DST problem.

File: examples/js/app.js (hunk 1 above)
Comment (jungeun-cho) [reply examples/js/app.js]: Yeah. I'll change.

`return currentDate.format(format);`
